
x-config: &x-config
  image: nginx:1.24.0
  restart: always
  logging:
    driver: "json-file"
    options:
      max-file: "1"
      max-size: "50m"
  volumes:
      - static:/my_tmp
      - ./local_static:/local_static

services:

  nginx1:
    <<: *x-config
    container_name: nginx1
    ports:
      - "81:80"

  nginx2:
    <<: *x-config
    container_name: nginx2
    # 假如有寫任何一行 volumes, 會完全附蓋掉 x-config 的 volumes
    volumes:
      - static_nginx_2:/tmp2
    ports:
      - "82:80"

  nginx3:
    <<: *x-config
    container_name: nginx3
    volumes:
      - static_nginx_3:/tmp3
      - static:/my_tmp  # 要再自己手動加上去
      - ./local_static:/local_static # 要再自己手動加上去
    ports:
      - "83:80"


volumes:
  static:
  static_nginx_2:
  static_nginx_3: